[cli]
auto_approve_tools = true
default_model = "GPT-5-Codex"
require_manual_approval = false

[mcp]
auto_approve = true
require_manual_approval = false

[[mcp.servers]]
args = ["agilai", "mcp"]
autoApprove = true
autoStart = true
command = "npx"
description = "Agilai MCP server for orchestrating Agilai agents."
displayName = "Agilai MCP"
name = "agilai-mcp"
transport = "stdio"

[[mcp.servers]]
args = ["@modelcontextprotocol/server-chrome-devtools@latest"]
autoApprove = false
autoStart = false
command = "npx"
description = "Optional Chrome DevTools recorder MCP server."
displayName = "Chrome DevTools MCP"
name = "chrome-devtools"
transport = "stdio"

[[mcp.servers]]
args = ["@shadcn/ui-cli@latest", "mcp"]
autoApprove = false
autoStart = false
command = "npx"
description = "Optional shadcn UI MCP helper (works with generated components.json)."
displayName = "shadcn UI MCP"
name = "shadcn"
transport = "stdio"
